force-app/main/default/objects/Boston_Housing_Data__c/Boston_Housing_Data__c.object-meta.xml
<CustomObject>
    <label>Boston Housing Data</label>
    <nameField>
        <label>Boston Housing Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boston Housing Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Age_Of_Housing__c.field-meta.xml
<CustomField>
    <fullName>Age_Of_Housing__c</fullName>
    <label>Age Of Housing</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Crime_Rate__c.field-meta.xml
<CustomField>
    <fullName>Crime_Rate__c</fullName>
    <label>Crime Rate</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Distance_To_Commute__c.field-meta.xml
<CustomField>
    <fullName>Distance_To_Commute__c</fullName>
    <label>Distance To Commute</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Distance_To_Highway__c.field-meta.xml
<CustomField>
    <fullName>Distance_To_Highway__c</fullName>
    <label>Distance To Highway</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Industrial_Proportion__c.field-meta.xml
<CustomField>
    <fullName>Industrial_Proportion__c</fullName>
    <label>Industrial Proportion</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Istest__c.field-meta.xml
<CustomField>
    <fullName>Istest__c</fullName>
    <label>Istest</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Land_Zone_Size__c.field-meta.xml
<CustomField>
    <fullName>Land_Zone_Size__c</fullName>
    <label>Land Zone Size</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Next_To_River__c.field-meta.xml
<CustomField>
    <fullName>Next_To_River__c</fullName>
    <label>Next To River</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Nitric_Oxide_Concentration__c.field-meta.xml
<CustomField>
    <fullName>Nitric_Oxide_Concentration__c</fullName>
    <label>Nitric Oxide Concentration</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Rooms_Per_House__c.field-meta.xml
<CustomField>
    <fullName>Rooms_Per_House__c</fullName>
    <label>Rooms Per House</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/School_Class_Size__c.field-meta.xml
<CustomField>
    <fullName>School_Class_Size__c</fullName>
    <label>School Class Size</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/School_Dropout_Rate__c.field-meta.xml
<CustomField>
    <fullName>School_Dropout_Rate__c</fullName>
    <label>School Dropout Rate</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Data__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boston_Housing_Target__c/Boston_Housing_Target__c.object-meta.xml
<CustomObject>
    <label>Boston Housing Target</label>
    <nameField>
        <label>Boston Housing Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boston Housing Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boston_Housing_Target__c/fields/Median_Value__c.field-meta.xml
<CustomField>
    <fullName>Median_Value__c</fullName>
    <label>Median Value</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BostonHousingController.cls
public with sharing class BostonHousingController {

    @AuraEnabled(cacheable=true)
    public static List<Boston_Housing_Data__c> findFeatures(String testKey) {
        return [
            SELECT 
                Crime_Rate__c,
                Land_Zone_Size__c,
                Industrial_Proportion__c,
                Next_To_River__c,
                Nitric_Oxide_Concentration__c,
                Rooms_Per_House__c,
                Age_Of_Housing__c,
                Distance_To_Commute__c,
                Distance_To_Highway__c,
                Tax_Rate__c, 
                School_Class_Size__c,
                School_Dropout_Rate__c
            FROM Boston_Housing_Data__c 
            WHERE Istest__c = :testKey
            ORDER BY Id ASC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Boston_Housing_Target__c> findTargets(String testKey) {
        return [
            SELECT 
                Median_Value__c
            FROM Boston_Housing_Target__c 
            WHERE Istest__c = :testKey
            ORDER BY Id ASC
        ];
    }
}